apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAsbfCbiqhcSbwYQAjp+FUWhDcSyYgxQ6lA+/rSM7uoR5qoJMD1ihMPLmHKi+c9erJGcOB/IscAa4ckIX7q6SxeAIMWKjv7K7ZHFUgLPLOqsVZxPx8i/8psJFzffjaNEwYcUceQ1QT3NLsBz6XX1O7OYgagQBm9Xsygm6dzntRDyZibEweDrYFPiUwG0YEiWE6tcS4llEaPWqW/ttJYtGkqjSn5+53iPkXhRH0XG6mesHCksdIi9IMsCqNZvrjo5uAJGkeX+sR20EZhVqqS93vKRVdAWgOGOk/PK8vMr6lOkuYBUGj/UVW7ZjqZNMDP1YRS0Jetcj4Qy4TRYPnXUhdFmRZIFIU865Qyap8gXxNU5pYNi3X8az8e1Be1qALpc+VuWVHZlW2Q5pNYfB3nxtkXJLcN7oLLNm7CEcGTV/71K78XWue/2vals0b4xQeaRbczkju7GsnCdqliBV/KHPI6jPItBEQSri3sDzXLnkd+1rCKDgrDfAKzMCxgKHjqUSdF6RC16QuDHwGPy/R4Oi3mueMbIAGMoxstnah4ZwoJrP66wSOaaE/6BMfZDNbNZntgO7MaGoaFzUzM1s3JwRKGgRq9xLghCWW1/LmyYIljkRmTNYzzKK49RNOwmp8jrh4Uf2ve3awZFMdkia8ZKvtdHIgtnvtRtts724V6TCbJe3imVUimAvcn7gU1ZoCqfojibOEWq3qWyA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

