apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBB9RN3H2FvLZkDxiNHcAVjumeOZawAITMco1b+bb0pfyRnlbXPbbdtNARwtmlsT4rvT3X2hFfCKX7mu1QSfxMN70lPKCZlGM74HWKjOmvI8EHxOJ6933HlD7Og5BdR2G0GURmGYLrx9eNpG0Our7Fwo3ImORgG6K3c8v8dzZHYxIF3TIrLH0xJ7uShEkAGPwr/8icMzOYNe2FuVmNGcrClkjhflvvn1vlfH3gFIqoKUxmhHWdTRSN7GKf23FIU/MwA1RJqNBKJCbzWT/KCQihiOPfnqhqUhjT3aSy7/6GS/tkTKYV2THpeuGH4b48hfm1MFVpqVM7+3gmhYUtJcyfN/D2N0BknjbPg9//M+cLtY00JmGKew6TyEE1fWpZAwVuoiIftjfJj7My9xYC+HC0pYtU8+en/0Ym+fZ12/viYZpXL3UKEISkgnQgZpy9+ripijdTrv/WXTWWD18zwZTynf9xTH6O4e0glnf3ZNw0lThTwMlyE/q2XJbZ98g7vM+txK08Iyy4TbMPp4ymGlU5rY3qGqOKyhZszRICwnOazhT++IYzP8VC3GMUxixiZLqpZHa4nLz5Q5YjlQp6fTHrpRYqN4EXyvG+tlYYgZzeJBb/d5bI3jrxzDcE4oPhbBP8gGo/cBS2inxmwh4PiPDDsQ99ZAO36rVVBRcvrG/m69zaAUZfKpFb8bKAakZuqy3WQBL4Oa+41UA==
    DB_USER: AgCqYNSUfUU6yTeLzTCziQMOqs9VZAEspDNAWSuhG8jOWvf0Srz0HMw89YdPKxr+MGFAXHz/u3YYlaklor5981oCLBs+MRGJwWndt4pjA7Xtjk0xz8xZ+hejhss6TMvr1V/Bd4hyKdLpn6sE5qsDgfZ1Pjypz7S0iFwq4JbfIIX1qIKT9SL/jY1V5JtQ4FJiJxHsjtrK701iWcETIuYLdowODokl+UTgXv0UbTaAXtapdFSeykqAk8nYk0dBnm1I3Fx0nffdGM2JYDlDb2QeMdoVHstpU6hVB003KFfeA4xWpeyi8IaLI7ir0Luh6MbbjG6ZOMlt/DfBdfj0C4Ps4PBeTyMins2Qyh0osBdrmZSwaMozeGIDCso6JgvUhKq9OQJNaYFxV9th2bKZbSR2k6LJbmS3ikHCt3di+raB6IAYyCXaZrC0mP7U7pqq2RZS/KYqPHwyOQJQ8J4dphRnm7Jbua7H0UOVDFuHQBXOn09TN8xiC85HEIKIUnbTILnRr3cgPHtFEcMbuN+314RhnkFS4EIgzkkjBHHE7nSP7MhnBbn2PEqfcG+ETJQE3cDZqQziPULQWfqs7zoszSc+GqBwxlKG7ERvYGjI0ZbddYZMsGbP7Udw7qf/b88k9zl9OmWrvfz/7yYUnHXfr0KaeSl4ibwkP+BQDL7nack0FVLG6LzC5mVW7sKgydU0qorwNssi/UbaciqXaA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

