kind: StatefulSet
apiVersion: apps/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '250'
  name: cd-63-ibm-connect-direct
  namespace: scd
  labels:
    app.kubernetes.io/instance: cd-63
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ibm-connect-direct
    argo.cntk/instance: ibm-sterling-connect-direct
    author: IBM
    helm.sh/chart: ibm-connect-direct-1.3.0
    release: cd-63
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cd-63
      app.kubernetes.io/name: ibm-connect-direct
      author: IBM
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cd-63
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ibm-connect-direct
        author: IBM
        helm.sh/chart: ibm-connect-direct-1.3.0
        release: cd-63
      annotations:
        checksum/config: 80b9b979da2ffb9befc945d0fd52bb459298068f14b2be3ee747e8f6d7dc3a60
        license: 'true'
        productChargedContainers: All
        productID: 0e99fe73c7ae4b799e11d00a9bbf0db0
        productMetric: VIRTUAL_PROCESSOR_CORE
        productName: IBM Sterling Connect Direct Premium Ed Certified Container
        productVersion: '6.3'
    spec:
      restartPolicy: Always
      serviceAccountName: cd-63-ibm-connect-direct-serviceaccount
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAffinity: {}
        podAntiAffinity: {}
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000710000
        runAsGroup: 1000710000
        runAsNonRoot: true
        supplementalGroups:
          - 65534
        fsGroup: 1000710000
      containers:
        - resources:
            limits:
              cpu: 500m
              ephemeral-storage: 5Gi
              memory: 2000Mi
            requests:
              cpu: 500m
              ephemeral-storage: 3Gi
              memory: 2000Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - /cdinstall/cdmonitor.sh 1363
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: cd-63-ibm-connect-direct
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - /cdinstall/cdmonitor.sh 1363
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          env:
            - name: CD_License_Acceptance
              value: 'true'
            - name: TZ
              value: UTC
            - name: SACL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: cd-63-ibm-connect-direct
                  key: saclConfig
            - name: CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: cd-63-ibm-connect-direct
                  resource: requests.cpu
                  divisor: '0'
            - name: LICENSE_TYPE
              value: prod
          securityContext:
            capabilities:
              add:
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                - AUDIT_WRITE
              drop:
                - ALL
            privileged: false
            runAsUser: 1000710000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - /cdinstall/cdmonitor.sh 1363
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - name: cd-vol
              mountPath: /opt/cdunix/ndm/cfg
              subPath: CFG
            - name: cd-vol
              mountPath: /opt/cdunix/work
              subPath: WORK
            - name: cd-vol
              mountPath: /opt/cdunix/ndm/secure+
              subPath: SECPLUS
            - name: cd-vol
              mountPath: /opt/cdunix/ndm/security
              subPath: SECURITY
            - name: cd-vol
              mountPath: /opt/cdunix/process
              subPath: PROCESS
            - name: cd-vol
              mountPath: /opt/cdunix/file_agent/config
              subPath: FACONFIG
            - name: cd-vol
              mountPath: /opt/cdunix/file_agent/log
              subPath: FALOG
            - name: cd-cert-secret
              readOnly: true
              mountPath: /opt/cdfiles/cdcert
            - name: cd-param
              readOnly: true
              mountPath: /opt/cdfiles/cd_param_file
              subPath: cd_param_file
            - name: cd-secret
              readOnly: true
              mountPath: /opt/cdfiles/secret_files
            - name: cd-vol
              mountPath: /opt/backup
              subPath: BACKUP
          terminationMessagePolicy: File
          image: >-
            cp.icr.io/cp/ibm-connectdirect/cdu6.3_certified_container_6.3.0.0:6.3.0.0_ifix000
      serviceAccount: cd-63-ibm-connect-direct-serviceaccount
      volumes:
        - name: cd-vol
          persistentVolumeClaim:
            claimName: cd-63-ibm-connect-direct-pvc
        - name: cd-param
          configMap:
            name: cd-63-ibm-connect-direct
            defaultMode: 292
        - name: cd-secret
          secret:
            secretName: cd-secret
            defaultMode: 292
        - name: cd-cert-secret
          secret:
            secretName: cd-cert-secret
            defaultMode: 292
      dnsPolicy: ClusterFirst
  serviceName: cd-63-ibm-connect-direct
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
status:
  observedGeneration: 1
  availableReplicas: 1
  updateRevision: cd-63-ibm-connect-direct-85cdcbb758
  currentRevision: cd-63-ibm-connect-direct-85cdcbb758
  currentReplicas: 1
  updatedReplicas: 1
  replicas: 1
  collisionCount: 0
  readyReplicas: 1
